package psk.practice.mybatis.model;

public class Character {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CHARACTER.ID
     *
     * @mbg.generated Sat Feb 13 22:17:58 EET 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CHARACTER.FIRSTNAME
     *
     * @mbg.generated Sat Feb 13 22:17:58 EET 2021
     */
    private String firstname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CHARACTER.LASTNAME
     *
     * @mbg.generated Sat Feb 13 22:17:58 EET 2021
     */
    private String lastname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CHARACTER.BOOK_ID
     *
     * @mbg.generated Sat Feb 13 22:17:58 EET 2021
     */
    private Integer bookId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CHARACTER.ID
     *
     * @return the value of PUBLIC.CHARACTER.ID
     *
     * @mbg.generated Sat Feb 13 22:17:58 EET 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CHARACTER.ID
     *
     * @param id the value for PUBLIC.CHARACTER.ID
     *
     * @mbg.generated Sat Feb 13 22:17:58 EET 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CHARACTER.FIRSTNAME
     *
     * @return the value of PUBLIC.CHARACTER.FIRSTNAME
     *
     * @mbg.generated Sat Feb 13 22:17:58 EET 2021
     */
    public String getFirstname() {
        return firstname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CHARACTER.FIRSTNAME
     *
     * @param firstname the value for PUBLIC.CHARACTER.FIRSTNAME
     *
     * @mbg.generated Sat Feb 13 22:17:58 EET 2021
     */
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CHARACTER.LASTNAME
     *
     * @return the value of PUBLIC.CHARACTER.LASTNAME
     *
     * @mbg.generated Sat Feb 13 22:17:58 EET 2021
     */
    public String getLastname() {
        return lastname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CHARACTER.LASTNAME
     *
     * @param lastname the value for PUBLIC.CHARACTER.LASTNAME
     *
     * @mbg.generated Sat Feb 13 22:17:58 EET 2021
     */
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CHARACTER.BOOK_ID
     *
     * @return the value of PUBLIC.CHARACTER.BOOK_ID
     *
     * @mbg.generated Sat Feb 13 22:17:58 EET 2021
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CHARACTER.BOOK_ID
     *
     * @param bookId the value for PUBLIC.CHARACTER.BOOK_ID
     *
     * @mbg.generated Sat Feb 13 22:17:58 EET 2021
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }
}